mod build;
mod checkpoint;
mod controller;
mod preflight;
mod references;
mod routes;
pub(crate) mod spec;
mod status;
mod timeouts;
mod tls_policy;
pub use controller::{Options, run};
pub(crate) use preflight::{PreviewInput, managed, validate};
pub use routes::{Policy, Routing};
pub const CONTROLLER: &str = "rgnix.io/gateway-controller";
pub const GROUP: &str = "gateway.networking.k8s.io";
