events {}
http {
    access_log ../.local/logs/access.log combined;
    error_log ../.local/logs/error.log warn;
    rgnix_log_rotation size=100m interval=1d keep=7 gzip=on;

    server {
        listen 8080;
        location / { return 200 "ok\n"; }
    }
}
